version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - "./data:/data/db"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
  chat:
    build: ./chatServer
    restart: always
    ports:
      - 4000:4000
    env_file:
      - ./chatServer/.env
    depends_on:
      - db
    links:
      - db
